### PR TITLE
Markers above/below pieces #65

### PR DESCRIPTION
**Pull request by lauracampoalberca**
Create "markers" extension to be positioned above or below the pieces.

### CODE REVIEW

**Comment by shaack** [comment]
Wow, these are some big changes. I like the idea to separate the markers to an extension because it makes the core more clean. Will take a closer look the next days. Thank you.

**Comment by vesper8** [comment]
Any update on this @shaack ? I also like the idea of abstracting markers to an extension and I like the added functionality that comes with this PR

**Comment by vesper8** [comment]
Any update on this @shaack ? I also like the idea of abstracting markers to an extension and I like the added functionality that comes with this PR

**Comment by shaack** [comment]
Merged into main branch, thank you @lauracampoalberca!

**Pull request merged**
