### PR TITLE
feat: Add an Arrows extension and accompanying hooks for new extensions

### PR DESCRIPTION
**Pull request by barakmich**
Opening this for discussion -- anyway, this creates an Arrows extension that allows for configurable arrowheads and styling. I tried to keep it as "extension" as I could.

Usage is something like this:

```
   const config = {
      position: "rn2k1r1/ppp1pp1p/3p2p1/5bn1/P7/2N2B2/1PPPPP2/2BNK1RR",
      extensions: [{
        class: Arrows,
        props: {
          overPieces: true,
        }
      }]
    };

    const chessboard = new Chessboard(document.getElementById(id), config);
    chessboard.addMarker("e6", MARKER_TYPE.frame)
    chessboard.addArrow("e4", "c2", ARROW_TYPE.pointy);
```

### CODE REVIEW

**Comment by barakmich** [comment]
Closes #69 #41

**Comment by shaack** [comment]
Thanks. Looks good from first sight. I will make a deeper review next week, because I am directly back from vacation and have some customer projects to do. A small thing to discuss for now maybe is, you made the `overPieces` configureable. Do you need also arrows below pieces? If not, I think, we could remove this configuration.

**Comment by shaack** [comment]
I think it would be good to separate the scss of extensions. Do you have an idea how this could be accomplished?

**Comment by shaack** [comment]
Maybe a folder per extension: https://github.com/shaack/cm-chessboard/issues/75 to put there the scss and the sprite

**Comment by shaack** [comment]
I like the `addMethod` Idea 👍 Will write some documentation for this in future.

**Pull request merged**
